# Generated by Django 3.1.7 on 2021-07-10 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioId', models.AutoField(db_column='usuario_id', primary_key=True, serialize=False, unique=True)),
                ('usuarioCorreo', models.EmailField(db_column='usuario_correo', max_length=30, unique=True, verbose_name='Correo del usuario')),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'USUARIO')], db_column='usuario_tipo', verbose_name='Tipo del usuario')),
                ('usuarioNombre', models.CharField(db_column='usuario_nombre', max_length=45, verbose_name='Nombre del usuario')),
                ('usuarioApellido', models.CharField(db_column='usuario_apellido', max_length=45, verbose_name='Apellido del usuario')),
                ('password', models.TextField(db_column='usuario_contrasena', verbose_name='Contraseña del usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 't_usuario',
            },
        ),
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('categoriaId', models.AutoField(db_column='categoria_id', primary_key=True, serialize=False)),
                ('categoriaNombre', models.CharField(db_column='categoria_nombre', max_length=40, verbose_name='Nombre de categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'db_table': 't_categoria',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('productoId', models.AutoField(db_column='producto_id', primary_key=True, serialize=False)),
                ('productoNombre', models.CharField(db_column='producto_nombre', max_length=50, verbose_name='Nombre del producto')),
                ('productoStock', models.IntegerField(db_column='producto_stock', verbose_name='Cantidad de los productos')),
                ('productoFoto', models.ImageField(db_column='producto_foto', upload_to='producto/', verbose_name='Foto del producto')),
                ('productoPrecio', models.DecimalField(db_column='producto_precio', decimal_places=2, max_digits=5, verbose_name='Precio del producto')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updateAt', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, to='administracion.categoriamodel')),
            ],
            options={
                'verbose_name': 'Producto',
                'db_table': 't_producto',
            },
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('pedidoId', models.AutoField(db_column='pedido_id', primary_key=True, serialize=False, unique=True)),
                ('pedidoFecha', models.DateField(db_column='pedido_fecha')),
                ('pedidoTipoPago', models.IntegerField(choices=[(1, 'EFECTIVO'), (2, 'TARJETA')], db_column='pedido_tipopago', verbose_name='Tipo de pago')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='productoPedido', to='administracion.productomodel')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarioPedido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedidos',
                'db_table': 't_pedido',
            },
        ),
    ]
