# Generated by Django 3.1.7 on 2021-07-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='pedidoCantidad',
            field=models.IntegerField(db_column='pedido_cantidad', default=1, verbose_name='Cantidad de los pedidos'),
            preserve_default=False,
        ),
    ]
