# Generated by Django 3.1.7 on 2021-07-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_pedidomodel_pedidocantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='pedidoCantidad',
            field=models.IntegerField(db_column='pedido_cantidad', verbose_name='Cantidad de los pedidos'),
        ),
    ]
