# Generated by Django 3.1.7 on 2021-07-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20210723_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomodel',
            name='productoFoto',
        ),
    ]
